### ISSUE TITLE
Feature Request: Read env vars from template

### ISSUE THREAD

**Issue by cjol** [duartemendes/aws-sam-api-proxy#8]
It's kind of annoying to have to add environment variables to a separate `envVars.json` file as well as to `template.yaml` - especially the ones that can otherwise be defined just once across all functions in `Globals.Function.Environment`. This would probably require adding some kind of support for `!Sub` command, so that we can pluck env values out of the host environment and thereby use local development values without polluting the `template.yaml` file.

**Comment by duartemendes** [comment]
Sorry for taking so long as I was away on vacations.

I defo see the benefit of having variables defined in the `Globals.Function.Environment` in order to avoid replicating all values in the `envVars.json` file.

In case of static values it would very easy to solve, the effort would be handling cloudformation intrinsic functions (Ref, Sub, etc). Not sure how much effort this would require. I'm happy to give some thoughts on this.

What did you mean by `pluck env values out of the host environment` exactly?

**Comment by cjol** [comment]
Hey, no problem. Hope it was a good break! We had a need to solve this for ourselves so I'm about to create a PR. 

By "plucking" I meant that if the host machine has an env var defined, then we would pass it into the function environments, so I could adjust the function environments with something like `DB_HOST=http://localhost:8000 sam-proxy start...`. In the end I didn't think this was very tidy, so I've gone for a different direction with a new `--parameters` parameter instead.
